#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE23B7E70B467F0BF (office@who-t.net)
#
Name     : xinput
Version  : 1.6.3
Release  : 4
URL      : https://www.x.org/releases/individual/app/xinput-1.6.3.tar.bz2
Source0  : https://www.x.org/releases/individual/app/xinput-1.6.3.tar.bz2
Source1  : https://www.x.org/releases/individual/app/xinput-1.6.3.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xinput-bin = %{version}-%{release}
Requires: xinput-license = %{version}-%{release}
Requires: xinput-man = %{version}-%{release}
BuildRequires : pkgconfig(inputproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xrandr)

%description
xinput
======
Overview
========
xinput is a utility to configure and test XInput devices. It wasn't
originally designed to be the primary tool for doing this but it's
still pretty much the only program out there for doing it. :-)

%package bin
Summary: bin components for the xinput package.
Group: Binaries
Requires: xinput-license = %{version}-%{release}

%description bin
bin components for the xinput package.


%package license
Summary: license components for the xinput package.
Group: Default

%description license
license components for the xinput package.


%package man
Summary: man components for the xinput package.
Group: Default

%description man
man components for the xinput package.


%prep
%setup -q -n xinput-1.6.3
cd %{_builddir}/xinput-1.6.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604442112
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604442112
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xinput
cp %{_builddir}/xinput-1.6.3/COPYING %{buildroot}/usr/share/package-licenses/xinput/c67b9687eea0526456367a5007e4f20fedf99eab
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xinput

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xinput/c67b9687eea0526456367a5007e4f20fedf99eab

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xinput.1
